apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yb8ovq7m0-java-quarkus
  janus-idp.io/tekton: yb8ovq7m0-java-quarkus
  backstage.io/kubernetes-id: yb8ovq7m0-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yb8ovq7m0-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
